[package]
name = "bbcore"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
getset = "0.1.5"
image = { version = "0.25.6", default-features = false, features = ["png"] }
imageproc = "0.25.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
